contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://shirazlug.gitlab.io"
title         = "ShirazLUG"
canonifyurls  = true
theme         = "Lanyon"

[indexes]
  category  = "categories"
