baseURL = "https://shirazlug.gitlab.io/"
languageCode = "en-us"
title = "شیراز لاگ"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Calin Tataru"
    description = "به شیراز لاگ خوش آمدید:) لاگ یه گروهی است از آدم های مختلف که به منظور تبادل اطلاعات در حوزه ی کامپیوتر دور هم جمع می شوند، اگر می خوای یه چیزی یاد بگیری یا صرفا کنجکاوی که چیزای جدیدی که اسمشون ر تا حالا نشنیدی رو بشنوی، یا از کنار چند تا آدم جالب بودن لذت ببری و حتی چند تا دوست پیدا کنی،با ما همراه باش"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" #vazir  # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "c++", "c", "python", "ruby"]

[[menu.main]]
    url = "/"
    name = "خانه"
    weight = 1

[[menu.main]]
    url = "/session/"
    name = "جلسه آینده"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "درباره ما"
    weight = 3

[[menu.main]]
    url = "/new/"
    name = "اخبار"
    weight = 4

[[menu.main]]
    url = "/event/"
    name = "رویداد ها"
    weight = 5

[[menu.main]]
    url = "/post/"
    name = "پست های آزاد"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://www.openstreetmap.org/?mlat=29.62499&mlon=52.52045#map=19/29.62499/52.52045"
    name = "map-marker"
    weight = 1

[[menu.icon]]
    url = "mailto:hadi@hirazlug.ir"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://telegram.me/joinchat/AYtPuT58Mz94GAd_-NxodQ"
    name = "telegram"
    weight = 3

#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "github"
#    weight =

[[menu.icon]]
    url = "https://twitter.com/LugShiraz"
    name = "twitter"
    weight = 4

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight =

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight =

[[menu.icon]]
    url = "https://gitlab.com/shirazlug"
    name = "gitlab"
    weight = 5
