baseURL = "https://shirazlug.gitlab.io/"
languageCode = "en-us"
title = "شیرازلاگ"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Calin Tataru"
    description = "به شیرازلاگ خوش آمدید :) لاگ گروهیست از افراد مختلف که به منظور تبادل اطلاعات در حوزه ی کامپیوتر دور هم جمع می شوند. اگر تمایل دارید دانش خود را با دیگران به اشتراک بگذارید یا کنجکاوید تا از موضوعات جدید اطلاعاتی کسب کنید و یا از بودن در کنار چند دوست کامپیوتری بااطلاع در حوزه های مختلف لذت می برید، پس با ما همراه شوید."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" #vazir  # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "c++", "c", "python", "ruby"]

[[menu.main]]
    url = "/"
    name = "خانه"
    weight = 6

[[menu.main]]
    url = "/session/"
    name = "جلسه‌های لاگ"
    weight = 5

[[menu.main]]
    url = "/about/"
    name = "درباره ما"
    weight = 4

[[menu.main]]
    url = "/new/"
    name = "اخبار"
    weight = 3

[[menu.main]]
    url = "/event/"
    name = "رویداد ها"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "پست های آزاد"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://www.openstreetmap.org/?mlat=29.62560&mlon=52.49326#map=19/29.62560/52.49326&layers=N"
    name = "map-marker"
    weight = 7

[[menu.icon]]
    url = "mailto:admin@shirazlug.ir"
    name = "envelope-o"
    weight = 6

[[menu.icon]]
    url = "https://telegram.me/joinchat/AYtPuT58Mz94GAd_-NxodQ"
    name = "telegram"
    weight = 5

[[menu.icon]]
    url = "https://github.com/shirazlug/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.instagram.com/lugshiraz/"
    name = "instagram"
    weight = 4


[[menu.icon]]
    url = "https://twitter.com/LugShiraz"
    name = "twitter"
    weight = 3


#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight =

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight =

[[menu.icon]]
    url = "https://gitlab.com/shirazlug"
    name = "gitlab"
    weight = 1
